apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - traefik.yaml
  - crd/ingressroute.yaml
  - crd/ingressroutetcp.yaml
  - crd/ingressrouteudp.yaml
  - crd/middlewares.yaml
  - crd/serverstransports.yaml
  - crd/tlsoptions.yaml
  - crd/tlsstores.yaml
  - crd/traefikservices.yaml
