additionalArguments:
- --providers.kubernetescrd.allowexternalnameservices=true
- --providers.kubernetescrd.allowCrossNamespace=false
- --log.level=DEBUG
- --accesslog=true
- --serverstransport.insecureskipverify=true
- --global.sendanonymoususage=false
ports:
  traefik:
    port: 9200
  websecure:
    expose: false
ingressRoute:
  dashboard:
    enabled: false
