additionalArguments:
  - --providers.kubernetescrd.allowexternalnameservices=true
  - --providers.kubernetescrd.allowCrossNamespace=false
  - --log.level=DEBUG
  - --accesslog=true
  - --serverstransport.insecureskipverify=true
  - --global.sendanonymoususage=false
  - --entryPoints.registry.address=:5000/tcp
  - --entryPoints.sshd.address=:2222/tcp

ingressRoute:
  dashboard:
    enabled: false

ports:
  traefik:
    port: 9200
  websecure:
    expose: false
