additionalArguments:
  - --providers.kubernetescrd.allowexternalnameservices=true
  - --providers.kubernetescrd.allowCrossNamespace=false
  - --log.level=DEBUG
  - --accesslog=true
  - --serverstransport.insecureskipverify=true
  - --global.sendanonymoususage=false
  - --entryPoints.registry.address=:5000/tcp
  - --entryPoints.sshd.address=:2222/tcp

ports:
  registry:
    port: 5000
    expose: true
    exposedPort: 5000
    protocol: TCP
  sshd:
    port: 2222
    expose: true
    exposedPort: 2222
    protocol: TCP
ingressRoute:
  dashboard:
    enabled: false

ports:
  traefik:
    port: 9200
  websecure:
    expose: false
