apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../upstream

resources:
  - namespace.yaml

patches:
  - path: patch-deployment-kuma-gateway.yaml
    target:
      kind: Deployment
      name: traefik
