additionalArguments:
  - --providers.file.filename=/data/traefik-config.yaml
  - --entryPoints.cloudflared.address=:8888/tcp
  - --entrypoints.websecure.http.middlewares=traefik-traefik-forward-auth 
  - --providers.kubernetescrd.allowexternalnameservices=true
  - --providers.kubernetescrd.allowCrossNamespace=false
  - --log.level=DEBUG
ports:
  web:
    redirectTo: websecure
ingressRoute:
  dashboard:
    enabled: false
