additionalArguments:
  - --providers.file.filename=/data/traefik-config.yaml
  - --entryPoints.cloudflared.address=:8888/tcp
  - --entrypoints.https.http.middlewares=traefik-traefik-forward-auth 
ports:
  web:
    redirectTo: websecure
ingressRoute:
  dashboard:
    enabled: false
