additionalArguments:
  - --providers.file.filename=/data/traefik-config.yaml
  - --entryPoints.dnstcp.address=:53/tcp
  - --entryPoints.dns.address=:53/udp
  - --entryPoints.cloudflared.address=:8888/tcp
ports:
  web:
    redirectTo: websecure
ingressRoute:
  dashboard:
    enabled: false
